# SPDX-License-Identifier: GPL-2.0-or-later

app_sources = files(
  'gimpruler.c',
  'about_dialog.c',
  'actionarea.c',
  'airbrush.c',
  'app_procs.c',
  'asupsample.c',
  'batch.c',
  'bezier_select.c',
  'blend.c',
  'boundary.c',
  'brightness_contrast.c',
  'brush_select.c',
  'brushes.c',
  'bucket_fill.c',
  'buildmenu.c',
  'by_color_select.c',
  'channel.c',
  'channel_cmds.c',
  'channels_dialog.c',
  'channel_ops.c',
  'clone.c',
  'color_area.c',
  'color_balance.c',
  'color_panel.c',
  'color_picker.c',
  'color_select.c',
  'color_transfer.c',
  'colormaps.c',
  'commands.c',
  'convert.c',
  'convolve.c',
  'crop.c',
  'cursorutil.c',
  'curves.c',
  'datafiles.c',
  'desaturate.c',
  'disp_callbacks.c',
  'draw_core.c',
  'drawable.c',
  'drawable_cmds.c',
  'edit_cmds.c',
  'edit_selection.c',
  'ellipse_select.c',
  'eraser.c',
  'errors.c',
  'equalize.c',
  'fileops.c',
  'flip_tool.c',
  'floating_sel.c',
  'floating_sel_cmds.c',
  'frac.c',
  'free_select.c',
  'fuzzy_select.c',
  'gdisplay.c',
  'gdisplay_cmds.c',
  'gdisplay_ops.c',
  'general.c',
  'gimage.c',
  'gimage_cmds.c',
  'gimage_mask.c',
  'gimage_mask_cmds.c',
  'gimprc.c',
  'global_edit.c',
  'gradient.c',
  'gximage.c',
  'histogram.c',
  'histogram_tool.c',
  'hue_saturation.c',
  'image_map.c',
  'image_render.c',
  'indexed_palette.c',
  'info_dialog.c',
  'info_window.c',
  'install.c',
  'interface.c',
  'internal_procs.c',
  'invert.c',
  'iscissors.c',
  'layer.c',
  'layer_cmds.c',
  'layer_select.c',
  'layers_dialog.c',
  'levels.c',
  'magnify.c',
  'main.c',
  'menus.c',
  'move.c',
  'ops_buttons.c',
  'palette.c',
  'paint_core.c',
  'paint_funcs.c',
  'paintbrush.c',
  'pattern_select.c',
  'patterns.c',
  'pencil.c',
  'perspective_tool.c',
  'pixel_region.c',
  'plug_in.c',
  'posterize.c',
  'procedural_db.c',
  'rect_select.c',
  'regex.c',
  'resize.c',
  'rotate_tool.c',
  'scale.c',
  'scale_tool.c',
  'scroll.c',
  'selection.c',
  'shear_tool.c',
  'temp_buf.c',
  'text_tool.c',
  'threshold.c',
  'tile.c',
  'tile_cache.c',
  'tile_manager.c',
  'tile_swap.c',
  'tips_dialog.c',
  'tools.c',
  'transform_core.c',
  'transform_tool.c',
  'undo.c',
  'undo_cmds.c',
  'xcf.c',
)

app_deps = [libgimpwidgets_dep, gtk_dep, glib_dep, gio_dep, cairo_dep,
            pango_dep, pixbuf_dep, m_dep]

app_c_args = ['-DREGEX_MALLOC']

gimp_exe = executable('gimp42',
  app_sources,
  gimpfeatures_h,
  link_with: libgimpwire,
  dependencies: app_deps,
  include_directories: gimp_inc,
  c_args: app_c_args,
  install: true,
  win_subsystem: 'windows',
)
